### ISSUE TITLE
Fonts are boring—let's update them!

### ISSUE THREAD

**Issue by tristandenyer** [tristandenyer/brewery-search#16]
The current fonts used are basic, and don't really convey much personality that goes with the context of a brewery search site.

Using a fast-loading font, or fonts, from Google, let's add some personality to the site!

@CCekla made some font suggestions in #15, breaking it out into a separate issue/ticket to make it smaller.

### If you want to work (or are working) on this issue, be sure to leave a comment here so others know.

**Comment by darrenrector91** [comment]
I've got something.  I'll put a request in but its just a change to the h1.
