### ISSUE TITLE
Missing favicon

### ISSUE THREAD

**Issue by tristandenyer** [tristandenyer/brewery-search#17]
We need to design, implement and test a favicon. 

### design
Something simple that connotes "brewery search". Can just be a beer mug, or hops, or ?

### implement
I highly recommend using the https://realfavicongenerator.net/ to get a robust and bulletproof list of meta tags and image assets to control how the favicon appears across devices. (One meta tag is not enough these days.) Once the design is made, simply upload the image and walk through the options on the next page. Vast majority of it is self-explanatory, but feel free to reach out here if you have questions.

### test
Once the favicon assets (there will be a lot) and the meta tags (equally a lot) are implemented, you can test that they work locally by showing up in the browser tab. Then we need to push it `master` branch which in turn pushes it to https://tristandenyer.github.io/brewery-search/. There we can runn that url through https://realfavicongenerator.net/favicon_checker to test that all the assets and meta tags are implemented correctly.

Thanks for spotting this @CCekla! (Broken out of #15 to make smaller.)

### If you want to work (or are working) on this issue, be sure to leave a comment here so others know.

**Comment by darrenrector91** [comment]
I got this

**Comment by albanmahmut** [comment]
Can I contribute?

**Comment by tristandenyer** [comment]
@albanmahmut Thank you for your interest in this issue. Looks like darrenrector91 already put in a PR for this. 

A couple options:
— when darrenrector91 makes his changes, you can feel free to do a code review and user acceptance test of his PR.
— Feel free to check out any of the other issues, or visit the demo and see if there are any additional issues or features you would like to propose.

Thanks again!

**Comment by tristandenyer** [comment]
Favicon merged in. Closing this.
