### ISSUE TITLE
Improve color palette

### ISSUE THREAD

**Issue by tristandenyer** [tristandenyer/brewery-search#8]
## This request is for

[x] Beginners
[x] First Timers
[x] Non-Coders (Designers welcome! We are looking for better colors here.)

## I'm submitting a...

[ ] Bug report
[ ] Feature request
[x] Enhancement on design/UI

## Current behavior
The demo can be viewed here: https://tristandenyer.github.io/brewery-search/

The hero area (top) is a beer-colored gradient, while the tops of the cards (do a search!) are just some random pale colors assigned to each of the following brewery types:
* Micro
* Contract
* Brewpub
* Large
* Regional
* Planning
* Proprietor

## Expected behavior

Choose better colors for the hero area and tops of cards.

## Important

Before you make a pull request, please comment on the issue that you would like to work on it. That way, we can avoid duplicate PRs and a first-timer can work on this. 

FYI: there is a great write-up on [how to work on this type of project and make your first PR here](https://gist.github.com/Chaser324/ce0505fbed06b947d962 "fhow to work on this type of project and make your first PR here.")

**Designers are welcome! A PR doesn't necessarily _have_ to be code.** You can use the comments section to suggest colors or design updates to the hero area and tops of cards. If someone else would like to work on it, they may take your color choices and implement them. Collaboration is awesome!

## Why is this an issue?

A couple reasons. One is that I want to support the [first-timers-only label](https://github.com/search?q=label%3Afirst-timers-only&state=open&type=Issues "first-timers-only label"), by offering up an approachable issue that I really need help with. 

Another is that I have never been on this side as an OSS project owner, and would like to get my feet wet.

**Comment by cSparkle** [comment]
Hello! I'd like to take this on. Just to clarify, you are only looking for color changes?
Warmly,
Cortney

**Comment by tristandenyer** [comment]
Thx @cSparkle ! This particular issue is set up to tackle just the color palette for the the two areas mentioned. If there is another improvement you would like to take in, please suggest it by creating a separate issue describing it and feel free to work on it. Thx!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tristandenyer** [comment]
NOTE: @Robin350 just submitted an interactive improvement to the hero area to mimic the action of a beer glass being filled. I merged it and you can see it in action here: https://tristandenyer.github.io/brewery-search/

**This ticket still stands. The colors of the hero area and the tops of cards still need some love.** 

All feedback is welcome!

**Comment by cSparkle** [comment]
Awesome! I'll get started on it soon.

**Comment by CCekla** [comment]
Hi! 
It's my very first time contributing to an open source (or even commenting on github tbh).
First of all I wanted to know if this was still open.
Then, since I don't seem to understand very well how pull requests work, I was wondering if it was ok to post here the hex codes (or a jpeg) for the palette. Also, you mentioned the possibility of "creating a separate issue" to suggest further improvements, do you mean new features or styling-wise?
Thank you (and sorry for the bad english)!
CC

**Comment by CCekla** [comment]
Ok! Thank you for your answer! :)

**Comment by tristandenyer** [comment]
Thx to the work of our contributors @cSparkle and @Robin350 I consider this particular issue closed. Will be reopening others that we have discovered during this process. Thanks again for all your hard work, and I hope you got to learn more about Git, Gitflow, GitHub, and PRs, as well as collaborating on an open source project with strangers. :)
